enable-delete-isolation-segments: false
enable-unassign-security-groups: false
skip-unassign-security-group-regex: ""
running-security-groups:
- default_security_group
staging-security-groups:
- default_security_group
shared-domains:
  apps.h2o-2-22900.h2o.vmware.com:
    internal: false
  apps.internal:
    internal: true
enable-remove-shared-domains: true
metadata-prefix: cf-mgmt.pivotal.io
enable-service-access: true
ignore-legacy-service-access: false
service-access:
- broker: smbbroker
  services:
  - service: smb
    no_access_plans:
    - Existing
- broker: app-autoscaler
  services:
  - service: app-autoscaler
    all_access_plans:
    - standard
- broker: nfsbroker
  services:
  - service: nfs
    no_access_plans:
    - Existing
  - service: nfs-legacy
    no_access_plans:
    - Existing
protected-users: []
