# your git repo uri
git_repo_uri: "https://github.com/Hermen-Nicolau/CF-MGMT.git"
git_repo_branch: main
# your cf system domain
system_domain: "sys.h2o-2-22900.h2o.vmware.com"
# user account with permission to create orgs/spaces
user_id: "cf-mgmt"
# DEPRECATED - Use client_secret - password of user account with permission to create orgs/spaces
password: ""
# client secret for uaa for user_id
client_secret: "Zu2B3jqruW6YOH@QAmE"

# logging level for cf-mgmt commands in the pipeline
log_level: INFO
# time interval to trigger update/delete jobs on
time-trigger: 15m

# configuration directory
config_dir: config

# allow specifying ldap server in pipeline vs in ldap.yml only needed if using LDAP
ldap_server: ""

# allow specifying ldap bind user in pipeline vs in ldap.yml only needed if using LDAP
ldap_user: ""

# password to bind to ldap - only needed if using LDAP
ldap_password: ""
